#!/bin/sh
case ${CONTROL_PLANE_CLEAN_SHELL-} in
  1) ;;
  *)
    exec /usr/bin/env -i CONTROL_PLANE_CLEAN_SHELL=1 LC_ALL=C PATH=/usr/bin:/bin \
      /bin/sh "$0" "$@"
    ;;
esac
set -eu

unset BASH_ENV ENV CDPATH || :

printf '%s\n' '{"authorizes":false,"error_code":"E_CAPABILITY_QUARANTINED","message":"Release candidate generation is quarantined in Control Plane Core.","ok":false}'
exit 2
